/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calcForms;

/**
 *
 * @author Izzy G. Osorio : nikaylez@gmail.com
 */
public class calcForm extends javax.swing.JFrame {

    /**
     * Creates new form calcForm
     */
    public calcForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        btn9 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        btn10 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        btn12 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        btn13 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        btn14 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        btn15 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        btn16 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        btn17 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        btn18 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        btn19 = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        btn20 = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        btn21 = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        btn22 = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        btn23 = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        btn24 = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        btn25 = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(23, 190, 187)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(0, 102, 102));
        jTextPane1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(0, 255, 0));
        jTextPane1.setText("0");
        jTextPane1.setCaretColor(new java.awt.Color(153, 153, 0));
        jTextPane1.setSelectedTextColor(new java.awt.Color(51, 0, 0));
        jScrollPane1.setViewportView(jTextPane1);

        btn9.setEditable(false);
        btn9.setBackground(new java.awt.Color(75, 29, 63));
        btn9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn9.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("  8  ");
        btn9.setToolTipText("");
        btn9.setFocusable(false);
        btn9.setName(""); // NOI18N
        jScrollPane2.setViewportView(btn9);

        btn10.setEditable(false);
        btn10.setBackground(new java.awt.Color(75, 29, 63));
        btn10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn10.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn10.setForeground(new java.awt.Color(255, 255, 255));
        btn10.setText("  7  ");
        btn10.setToolTipText("");
        btn10.setFocusable(false);
        btn10.setName(""); // NOI18N
        jScrollPane3.setViewportView(btn10);

        btn12.setEditable(false);
        btn12.setBackground(new java.awt.Color(75, 29, 63));
        btn12.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn12.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn12.setForeground(new java.awt.Color(255, 255, 255));
        btn12.setText("  4  ");
        btn12.setToolTipText("");
        btn12.setFocusable(false);
        btn12.setName(""); // NOI18N
        jScrollPane5.setViewportView(btn12);

        btn13.setEditable(false);
        btn13.setBackground(new java.awt.Color(75, 29, 63));
        btn13.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn13.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn13.setForeground(new java.awt.Color(255, 255, 255));
        btn13.setText("  5  ");
        btn13.setToolTipText("");
        btn13.setFocusable(false);
        btn13.setName(""); // NOI18N
        jScrollPane6.setViewportView(btn13);

        btn14.setEditable(false);
        btn14.setBackground(new java.awt.Color(75, 29, 63));
        btn14.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn14.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn14.setForeground(new java.awt.Color(255, 255, 255));
        btn14.setText("  6  ");
        btn14.setToolTipText("");
        btn14.setFocusable(false);
        btn14.setName(""); // NOI18N
        jScrollPane7.setViewportView(btn14);

        btn15.setEditable(false);
        btn15.setBackground(new java.awt.Color(75, 29, 63));
        btn15.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn15.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn15.setForeground(new java.awt.Color(255, 255, 255));
        btn15.setText("  1  ");
        btn15.setToolTipText("");
        btn15.setFocusable(false);
        btn15.setName(""); // NOI18N
        btn15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn15MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(btn15);

        btn16.setEditable(false);
        btn16.setBackground(new java.awt.Color(75, 29, 63));
        btn16.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn16.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn16.setForeground(new java.awt.Color(255, 255, 255));
        btn16.setText("  3  ");
        btn16.setToolTipText("");
        btn16.setFocusable(false);
        btn16.setName(""); // NOI18N
        jScrollPane9.setViewportView(btn16);

        btn17.setEditable(false);
        btn17.setBackground(new java.awt.Color(75, 29, 63));
        btn17.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn17.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn17.setForeground(new java.awt.Color(255, 255, 255));
        btn17.setText("  2  ");
        btn17.setToolTipText("");
        btn17.setFocusable(false);
        btn17.setName(""); // NOI18N
        jScrollPane10.setViewportView(btn17);

        btn18.setEditable(false);
        btn18.setBackground(new java.awt.Color(75, 29, 63));
        btn18.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn18.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn18.setForeground(new java.awt.Color(255, 255, 255));
        btn18.setText("  9  ");
        btn18.setToolTipText("");
        btn18.setFocusable(false);
        btn18.setName(""); // NOI18N
        jScrollPane11.setViewportView(btn18);

        btn19.setEditable(false);
        btn19.setBackground(new java.awt.Color(0, 204, 0));
        btn19.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn19.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn19.setForeground(new java.awt.Color(255, 255, 255));
        btn19.setText("  =  ");
        btn19.setToolTipText("");
        btn19.setFocusable(false);
        btn19.setName(""); // NOI18N
        jScrollPane12.setViewportView(btn19);

        btn20.setEditable(false);
        btn20.setBackground(new java.awt.Color(0, 51, 51));
        btn20.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn20.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn20.setForeground(new java.awt.Color(255, 255, 255));
        btn20.setText("  /  ");
        btn20.setToolTipText("");
        btn20.setFocusable(false);
        btn20.setName(""); // NOI18N
        jScrollPane13.setViewportView(btn20);

        btn21.setEditable(false);
        btn21.setBackground(new java.awt.Color(0, 51, 51));
        btn21.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn21.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn21.setForeground(new java.awt.Color(255, 255, 255));
        btn21.setText("  *  ");
        btn21.setToolTipText("");
        btn21.setFocusable(false);
        btn21.setName(""); // NOI18N
        jScrollPane14.setViewportView(btn21);

        btn22.setEditable(false);
        btn22.setBackground(new java.awt.Color(0, 51, 51));
        btn22.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn22.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn22.setForeground(new java.awt.Color(255, 255, 255));
        btn22.setText("  -  ");
        btn22.setToolTipText("");
        btn22.setFocusable(false);
        btn22.setName(""); // NOI18N
        jScrollPane15.setViewportView(btn22);

        btn23.setEditable(false);
        btn23.setBackground(new java.awt.Color(0, 51, 51));
        btn23.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn23.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn23.setForeground(new java.awt.Color(255, 255, 255));
        btn23.setText("  +  ");
        btn23.setToolTipText("");
        btn23.setFocusable(false);
        btn23.setName(""); // NOI18N
        jScrollPane16.setViewportView(btn23);

        btn24.setEditable(false);
        btn24.setBackground(new java.awt.Color(75, 29, 63));
        btn24.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn24.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn24.setForeground(new java.awt.Color(255, 255, 255));
        btn24.setText("  0  ");
        btn24.setToolTipText("");
        btn24.setFocusable(false);
        btn24.setName(""); // NOI18N
        btn24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn24MouseClicked(evt);
            }
        });
        jScrollPane17.setViewportView(btn24);

        btn25.setEditable(false);
        btn25.setBackground(new java.awt.Color(255, 0, 0));
        btn25.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), new java.awt.Color(51, 255, 204)));
        btn25.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        btn25.setForeground(new java.awt.Color(255, 255, 255));
        btn25.setText("  C  ");
        btn25.setToolTipText("");
        btn25.setFocusable(false);
        btn25.setName(""); // NOI18N
        btn25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn25MouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(btn25);

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alguna anotacion por aqui :)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn15MouseClicked
        // TODO add your handling code here:
        jTextPane1.setText(String.valueOf("1"));
    }//GEN-LAST:event_btn15MouseClicked

    private void btn24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn24MouseClicked
        // TODO add your handling code here:
        jTextPane1.setText(String.valueOf("0"));
    }//GEN-LAST:event_btn24MouseClicked

    private void btn25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn25MouseClicked
        // TODO add your handling code here:
        jTextPane1.setText(String.valueOf(""));
    }//GEN-LAST:event_btn25MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane btn10;
    private javax.swing.JTextPane btn12;
    private javax.swing.JTextPane btn13;
    private javax.swing.JTextPane btn14;
    private javax.swing.JTextPane btn15;
    private javax.swing.JTextPane btn16;
    private javax.swing.JTextPane btn17;
    private javax.swing.JTextPane btn18;
    private javax.swing.JTextPane btn19;
    private javax.swing.JTextPane btn20;
    private javax.swing.JTextPane btn21;
    private javax.swing.JTextPane btn22;
    private javax.swing.JTextPane btn23;
    private javax.swing.JTextPane btn24;
    private javax.swing.JTextPane btn25;
    private javax.swing.JTextPane btn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
